language: node_js
node_js:
  - "10.1"
cache: npm
# safelist
branches:
  only:
  - master
script:
  - echo "installing dependencies functions"
  - npm install --prefix ./functions
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  message: "deploying"